# Generated by Django 4.2.2 on 2023-06-24 17:08

from django.db import migrations, models
import django.db.models.deletion
import generic_storage.models
import taggit.managers
import uuid
import vscode_marketplace.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                ("statistics", models.JSONField()),
                ("released", models.DateTimeField()),
                ("published", models.DateTimeField()),
                ("flags", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GalleryExtensionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="GalleryExtensionPublisher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("domain", models.CharField(max_length=255, null=True)),
                ("domain_verified", models.BooleanField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GalleryExtensionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="GalleryExtensionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", vscode_marketplace.models.SemVerField(max_length=255)),
                ("last_updated", models.DateTimeField()),
                ("target_platform", models.CharField(max_length=100, null=True)),
                (
                    "extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vscode_marketplace.galleryextension",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryExtensionTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vscode_marketplace.galleryextension",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="vscode_marketplace.galleryextensiontag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryExtensionProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "extension_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vscode_marketplace.galleryextensionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "GalleryExtensionProperty",
                "verbose_name_plural": "GalleryExtensionProperties",
            },
        ),
        migrations.CreateModel(
            name="GalleryExtensionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("source", models.URLField(null=True)),
                (
                    "file",
                    generic_storage.models.GenericStorageFileField(
                        storage=vscode_marketplace.models._get_storage, upload_to=""
                    ),
                ),
                ("storage", models.CharField(max_length=255, null=True)),
                (
                    "extension_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vscode_marketplace.galleryextensionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryExtensionCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vscode_marketplace.galleryextension",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="vscode_marketplace.galleryextensioncategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="galleryextension",
            name="categories",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="vscode_marketplace.GalleryExtensionCategories",
                to="vscode_marketplace.GalleryExtensionCategory",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="galleryextension",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extension",
                to="vscode_marketplace.galleryextensionpublisher",
            ),
        ),
        migrations.AddField(
            model_name="galleryextension",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="vscode_marketplace.GalleryExtensionTags",
                to="vscode_marketplace.GalleryExtensionTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddConstraint(
            model_name="galleryextensionversion",
            constraint=models.UniqueConstraint(
                fields=("version", "extension"), name="gallery_extension_version_uid"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="galleryextensiontags",
            unique_together={("content_object", "tag")},
        ),
        migrations.AddConstraint(
            model_name="galleryextensionproperty",
            constraint=models.UniqueConstraint(
                fields=("extension_version", "key"),
                name="gallery_extension_property_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="galleryextensionfile",
            constraint=models.UniqueConstraint(
                fields=("extension_version", "type", "storage"),
                name="gallery_extension_file_uid",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="galleryextensioncategories",
            unique_together={("content_object", "tag")},
        ),
        migrations.AddConstraint(
            model_name="galleryextension",
            constraint=models.UniqueConstraint(
                fields=("name", "publisher"), name="gallery_extension_unique_name"
            ),
        ),
    ]
